# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="SHLOMIF"
MODULE_VERSION="1.0004"


inherit perl-module

DESCRIPTION="Perl extension for comparing XML documents."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/XML-Parser
	>=dev-perl/Module-Build-0.420.500
	dev-lang/perl"
