# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="RJBS"
MODULE_VERSION="0.020"


inherit perl-module

DESCRIPTION="composable units of assertion"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Moose
	dev-perl/namespace-clean
	dev-perl/Class-Load
	dev-perl/Sub-Exporter
	dev-perl/Params-Util
	dev-perl/Test-Fatal
	dev-perl/namespace-autoclean
	dev-perl/Try-Tiny
	dev-lang/perl"
