# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="ABW"
MODULE_VERSION="2.7"


inherit perl-module

DESCRIPTION="Plugin interface to Data::Dumper"
SRC_URI="http://search.cpan.org/CPAN/authors/id/A/AB/ABW/Template-Toolkit-2.26.tar.gz"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="
	dev-perl/Template-Plugin
	dev-lang/perl
"
