# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="TOBYINK"
MODULE_VERSION="0.105"


inherit perl-module

DESCRIPTION="make HTML5 DOM trees less insane"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/XML-LibXML-2.12.100
	>=perl-gcpan/HTML-HTML5-Parser-0.301
	perl-gcpan/XML-LibXML-Debugging
	dev-lang/perl"
