# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="TOBYINK"
MODULE_VERSION="0.103"


inherit perl-module

DESCRIPTION="get debugging information from XML::LibXML nodes"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="perl-gcpan/HTML-HTML5-Entities
	dev-perl/XML-LibXML
	dev-lang/perl"
