# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="DAGOLDEN"
MODULE_VERSION="1.001"


inherit perl-module

DESCRIPTION="Fast random UUID generator using the Mersenne Twister algorithm"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/List-AllUtils
	perl-gcpan/Math-Random-MT-Auto
	dev-lang/perl"
