# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="DWHEELER"
MODULE_VERSION="0.16"


inherit perl-module

DESCRIPTION="No description available"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=">=dev-perl/HTML-Selector-XPath-0.18
	>=dev-perl/Module-Build-0.420.500
	>=dev-perl/Test-Pod-1.480.0
	>=dev-perl/Test-Pod-Coverage-1.80.0
	>=dev-perl/XML-LibXML-2.12.100
	dev-lang/perl"
