# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="DEXTER"
MODULE_VERSION="0.0303"


inherit perl-module

DESCRIPTION="Simulating other classes"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Class-Inspector
	dev-perl/namespace-clean
	>=dev-perl/Moose-2.60.400
	dev-perl/Fatal-Exception
	dev-perl/Exception-Base
	>=dev-perl/Test-Unit-Lite-0.120.200
	>=dev-perl/Test-Assert-0.50.400
	dev-lang/perl"
