# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="JDHEDDEN"
MODULE_VERSION="6.22"


inherit perl-module

DESCRIPTION="Auto-seeded Mersenne Twister PRNGs"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

# Why is a Windows API being pulled in?
#perl-gcpan/Win32-API
DEPEND=">=dev-perl/Exception-Class-1.390.0
	dev-lang/perl"
