# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="STEVENL"
MODULE_VERSION="0.11"


inherit perl-module

DESCRIPTION="Mocking framework with method stubs and behaviour verification"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Moose
	dev-perl/aliased
	dev-perl/namespace-autoclean
	perl-gcpan/UNIVERSAL-ref
	dev-perl/Throwable
	dev-perl/Devel-PartialDump
	dev-perl/Set-Object
	dev-perl/Test-Fatal
	dev-perl/MooseX-Types-Structured
	dev-perl/MooseX-Types
	dev-lang/perl"
