# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="MMORGAN"
MODULE_VERSION="1.10"
MODULE_A_EXT="tgz"

inherit perl-module

DESCRIPTION="Permits recording, and later playing back of LWP requests."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

S="${WORKDIR}/${PN}"

DEPEND="dev-perl/URI
	dev-perl/Hook-LexWrap
	dev-lang/perl"
