# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.6

EAPI=5

MODULE_AUTHOR="BULKDD"
MODULE_VERSION="0.82"

MODULE_SECTION="Win32"

inherit perl-module

DESCRIPTION="Perl Win32 API Import Facility"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-perl/Encode-compat
	perl-gcpan/Math-Int64
	perl-gcpan/Win32API-File
	dev-lang/perl"
